### ISSUE TITLE
Remove bootstrap dependency from nuspec

### ISSUE THREAD

**Issue by tomgruszowski** [faulknercs/Knockstrap#47]
Many people use the LESS version of bootstrap (as well as a few others), making it extremely annoying when updating packages that depend on the basic version. I don't think anyone is going to accidentally use this code without including bootstrap. If it's needed for tests that's another thing.

Please consider removing this.

**Comment by faulknercs** [comment]
Hello,

I have included Bootstrap as dependency, because Knockstrap uses not only Bootstrap's styles, but javascript too. So I thought, that it will be semantically more correct to have this dependency.

But since bootstrap has several different packages (like less/css), I begin to thinking, that removing that dependency is good idea. Think, I will remove it in next version, thanks for that suggestion.

Best regards,
Artem
